# Generated by Django 2.2.24 on 2021-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20211027_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='observacao',
            field=models.CharField(max_length=128, verbose_name='Motivo'),
        ),
    ]
